- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: Print Course Info
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}} with AWS, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"
