- name: variables from files
  hosts: web
  # vars:  #Play level variables
  #   COURSE: "DevOps With AWS from play level"
  #   TRAINER: "SivakumarReddy"
  #   DURATION: "120HRS" 
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: COURSE
  #   prompt: Please enter the course name
  #   private: false # not confidential   
  tasks:
  - name: Print Course Info
    vars:  #Play level variables
      #COURSE: "DevOps With AWS from Task level"
      TRAINER: "SivakumarReddy"
      DURATION: "120HRS"  
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}"




#preference list below


#1. command line/args
#2. Task level
#3. Files
#4. prompt
#5. Play
#6. inventory
#7. Roles
